// JsFromRoutes CacheKey 6429a22709798159bf185de80064dc61
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/signup'),
}
